version: '3.8'
services:
  lumiora-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: lumiora_db
    volumes:
      - mysql_data:/var/lib/mysql
    # The crucial healthcheck that the backend and cms are waiting for!
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      lumiora-db:
        condition: service_healthy
    volumes:
      - ./backend/public/images:/app/public/images

  cms:
    build: ./cms
    ports:
      - "8000:8000"
    depends_on:
      lumiora-db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./cms:/app
  
  pipeline:
    build: ./pipeline
    depends_on:
      lumiora-db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=${DB_PASSWORD}

  station:
      build:
        context: ./station
        dockerfile: Dockerfile
      container_name: lumiora-station
      ports:
        - "5173:5173"
      environment:
        - CHOKIDAR_USEPOLLING=true
        - PORT=5173 
      volumes:
        - ./station:/app
        - /app/node_modules
      command: sh -c "npm install && npm run dev -- --host" 
      depends_on:
        - backend

volumes:
  mysql_data: