version: '3.8'
services:
  lumiora-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lumiora_db
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - lumiora-db
    volumes:
      - ./backend/public/images:/app/public/images

volumes:
  mysql_data: